In [ ]:
import pandas as pd
import datetime
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import functools as reduce
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
from matplotlib import pyplot as plt


In [ ]:
ratings = pd.read_csv("2020-08-19.csv", encoding = 'unicode_escape')
reviews = pd.read_csv("bgg-15m-reviews.csv", engine='python', error_bad_lines=False) 


In [ ]:
ratings.head()

Index  ...                                          Thumbnail
0     90  ...  https://cf.geekdo-images.com/micro/img/0m3-oqB...
1    172  ...  https://cf.geekdo-images.com/micro/img/z0tTaij...
2    380  ...  https://cf.geekdo-images.com/micro/img/e0y6Bog...
3     49  ...  https://cf.geekdo-images.com/micro/img/h-Ejv31...
4     87  ...  https://cf.geekdo-images.com/micro/img/VYp2s2f...

[5 rows x 10 columns]

In [ ]:
ratings_1 = ratings.drop(['URL',"Thumbnail"], axis = 1)
#subset -url, thumbnail

In [ ]:
ratings.isna().sum()

Index             0
ID                0
Name              0
Year              0
Rank              0
Average           0
Bayes average     0
Users rated       0
URL               0
Thumbnail        13
dtype: int64

In [ ]:
ratings_count = ratings.count()

In [ ]:
ratings_count

Index            19330
ID               19330
Name             19330
Year             19330
Rank             19330
Average          19330
Bayes average    19330
Users rated      19330
URL              19330
Thumbnail        19317
dtype: int64

In [ ]:
len(ratings)

19330

In [ ]:
reviews = pd.read_csv("bgg-15m-reviews.csv", engine='python', error_bad_lines=False) 

In [ ]:
reviews.head()

Unnamed: 0             user  ...       ID      name
0           0          Torsten  ...  30549.0  Pandemic
1           1  mitnachtKAUBO-I  ...  30549.0  Pandemic
2           2           avlawn  ...  30549.0  Pandemic
3           3       Mike Mayer  ...  30549.0  Pandemic
4           4          Mease19  ...  30549.0  Pandemic

[5 rows x 6 columns]

In [ ]:
reviews_1 = reviews.rename( columns={'Unnamed: 0':'Index'})

In [ ]:
reviews_1.head()

Index             user  ...       ID      name
0      0          Torsten  ...  30549.0  Pandemic
1      1  mitnachtKAUBO-I  ...  30549.0  Pandemic
2      2           avlawn  ...  30549.0  Pandemic
3      3       Mike Mayer  ...  30549.0  Pandemic
4      4          Mease19  ...  30549.0  Pandemic

[5 rows x 6 columns]

In [ ]:
for col in reviews_1.columns:
    pct_missing = np.mean(reviews_1[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

Index - 0%
user - 0%
rating - 0%
comment - 82%
ID - 0%
name - 0%


In [ ]:
reviews_1.isna().sum()

Index           0
user            0
rating          1
comment    490621
ID              1
name            1
dtype: int64

In [ ]:
reviews_1.count()

Index      597751
user       597751
rating     597750
comment    107130
ID         597750
name       597750
dtype: int64

In [ ]:
reviews_1.comment = reviews_1.comment.fillna('')

In [ ]:
reviews_1.user = reviews_1.user.fillna("Anonymous")

In [ ]:
reviews_1[(reviews_1.user == "Anonymous")]

Empty DataFrame
Columns: [Index, user, rating, comment, ID, name]
Index: []

In [ ]:
reviews_1.isna().sum()

Index      0
user       0
rating     1
comment    0
ID         1
name       1
dtype: int64

In [ ]:
len(reviews_1)

597751

In [ ]:
reviews_1.isna().sum()

Index      0
user       0
rating     1
comment    0
ID         1
name       1
dtype: int64

In [ ]:
ratings_1.isna().sum()

Index            0
ID               0
Name             0
Year             0
Rank             0
Average          0
Bayes average    0
Users rated      0
dtype: int64

In [ ]:
ratings_1

Index      ID  ... Bayes average  Users rated
0         90   30549  ...         7.518        96186
1        172     822  ...         7.311        96181
2        380      13  ...         7.001        96171
3         49   68448  ...         7.662        79830
4         87   36218  ...         7.521        74933
...      ...     ...  ...           ...          ...
19325  16923  246345  ...         5.490           30
19326  13931  195623  ...         5.515           30
19327  16638  235943  ...         5.493           30
19328  13932  284862  ...         5.515           30
19329  12882  281515  ...         5.522           30

[19330 rows x 8 columns]

In [ ]:
ratings_1[(ratings_1.Name== "Pandemic")]

Index     ID      Name  Year  Rank  Average  Bayes average  Users rated
0     90  30549  Pandemic  2008    91     7.62          7.518        96186

In [ ]:
reviews_1

Index             user  ...       ID      name
0            0          Torsten  ...  30549.0  Pandemic
1            1  mitnachtKAUBO-I  ...  30549.0  Pandemic
2            2           avlawn  ...  30549.0  Pandemic
3            3       Mike Mayer  ...  30549.0  Pandemic
4            4          Mease19  ...  30549.0  Pandemic
...        ...              ...  ...      ...       ...
597746  597746         Septaron  ...  39856.0     Dixit
597747  597747            Gizah  ...  39856.0     Dixit
597748  597748          eyeurn1  ...  39856.0     Dixit
597749  597749  Darius van Duyn  ...  39856.0     Dixit
597750  597750    ShinyHappyMee  ...      NaN      None

[597751 rows x 6 columns]

In [ ]:
reviews_1[(reviews_1.name == "Pandemic")]

Index             user  ...       ID      name
0            0          Torsten  ...  30549.0  Pandemic
1            1  mitnachtKAUBO-I  ...  30549.0  Pandemic
2            2           avlawn  ...  30549.0  Pandemic
3            3       Mike Mayer  ...  30549.0  Pandemic
4            4          Mease19  ...  30549.0  Pandemic
...        ...              ...  ...      ...       ...
596042  596042         jgilmour  ...  30549.0  Pandemic
596043  596043          miah999  ...  30549.0  Pandemic
596044  596044      thelonewolf  ...  30549.0  Pandemic
596045  596045           antrim  ...  30549.0  Pandemic
596046  596046         CcrunchM  ...  30549.0  Pandemic

[6050 rows x 6 columns]

In [ ]:
merge_rr = pd.merge(ratings_1,reviews_1, on= "ID")

In [ ]:
merge_rr

Index_x  ...                                            name
0            90  ...                                        Pandemic
1            90  ...                                        Pandemic
2            90  ...                                        Pandemic
3            90  ...                                        Pandemic
4            90  ...                                        Pandemic
...         ...  ...                                             ...
597745      103  ...  Descent: Journeys in the Dark (Second Edition)
597746      103  ...  Descent: Journeys in the Dark (Second Edition)
597747      103  ...  Descent: Journeys in the Dark (Second Edition)
597748      103  ...  Descent: Journeys in the Dark (Second Edition)
597749      103  ...  Descent: Journeys in the Dark (Second Edition)

[597750 rows x 13 columns]

In [ ]:
len(merge_rr)

597750

In [ ]:
merge_rr[(merge_rr.ID == 30549)]

Index_x  ...      name
0          90  ...  Pandemic
1          90  ...  Pandemic
2          90  ...  Pandemic
3          90  ...  Pandemic
4          90  ...  Pandemic
...       ...  ...       ...
6045       90  ...  Pandemic
6046       90  ...  Pandemic
6047       90  ...  Pandemic
6048       90  ...  Pandemic
6049       90  ...  Pandemic

[6050 rows x 13 columns]

In [ ]:
merge_rr.head(2)

Index_x     ID  ...                                            comment      name
0       90  30549  ...                                                     Pandemic
1       90  30549  ...  Hands down my favorite new game of BGG CON 200...  Pandemic

[2 rows x 13 columns]

In [ ]:
merge_rr = merge_rr.drop(["name","Index_x", "Index_y"], axis = 1)

In [ ]:
merge_rr.head(2)

ID      Name  ...  rating                                            comment
0  30549  Pandemic  ...    10.0                                                   
1  30549  Pandemic  ...    10.0  Hands down my favorite new game of BGG CON 200...

[2 rows x 10 columns]

In [ ]:
#Data Exploration

In [ ]:
#PCA

In [ ]:
pca_df = merge_rr.drop(["Name","user","comment"], axis = 1)

In [ ]:
pca_df.head(2)

ID  Year  Rank  Average  Bayes average  Users rated  rating
0  30549  2008    91     7.62          7.518        96186    10.0
1  30549  2008    91     7.62          7.518        96186    10.0

In [ ]:
pca_df.columns

Index(['ID', 'Year', 'Rank', 'Average', 'Bayes average', 'Users rated',
       'rating'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=MinMaxScaler()


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
pca_df.dtypes

ID                 int64
Year               int64
Rank               int64
Average          float64
Bayes average    float64
Users rated        int64
rating           float64
dtype: object

In [ ]:
trainpca = pca_df.drop(["rating"], axis = 1)
testpca = pca_df['rating']
X_trainp, X_testp, y_trainp, y_testp = train_test_split(trainpca, testpca, test_size=0.3, random_state=1)

In [ ]:
X_trainp = scaler.fit_transform(X_trainp)
X_testp = scaler.transform(X_testp)

In [ ]:
pca = PCA()
pca.fit(X_trainp)
print(pca.explained_variance_ratio_)
np.set_printoptions(suppress=True) 

[4.73701720e-01 2.91470202e-01 1.51272044e-01 4.65807254e-02
 3.68467343e-02 1.28574471e-04]


In [ ]:
pca.n_components_

6

In [ ]:
pca6 = PCA(n_components=6)
pca6.fit(X_trainp)
print(pca6.explained_variance_ratio_)

[0.47370172 0.2914702  0.15127204 0.04658073 0.03684673 0.00012857]


In [ ]:
print(pca6.components_)

[[-0.84477331 -0.09871402  0.21585988 -0.32862312 -0.32989224  0.11487414]
 [-0.17972212  0.04794391 -0.24621304  0.28115143  0.30301627  0.85668868]
 [ 0.48439776  0.03179558  0.46764722 -0.3861209  -0.38606212  0.49751443]
 [ 0.07751633 -0.9863513   0.07950903  0.08593031  0.07665279  0.03899973]
 [-0.11577117  0.11835327  0.81714641  0.38962009  0.38649804 -0.06063614]
 [-0.00225367  0.00704155 -0.00630737  0.71041082 -0.70359925  0.01304255]]


In [ ]:
pca_df.corr(method ="pearson")


ID      Year  ...  Users rated    rating
ID             1.000000  0.251322  ...    -0.171630  0.157296
Year           0.251322  1.000000  ...     0.060429  0.037550
Rank          -0.219281 -0.160339  ...    -0.102032 -0.426646
Average        0.438727  0.209059  ...     0.138504  0.643263
Bayes average  0.427321  0.215648  ...     0.168337  0.643936
Users rated   -0.171630  0.060429  ...     1.000000  0.358126
rating         0.157296  0.037550  ...     0.358126  1.000000

[7 rows x 7 columns]

In [ ]:
from sklearn import linear_model

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
pca_df.columns

Index(['ID', 'Year', 'Rank', 'Average', 'Bayes average', 'Users rated',
       'rating'],
      dtype='object')

In [ ]:
train = pca_df.drop(["rating"], axis = 1)
test = pca_df["rating"]
X_train, X_test, y_train, y_test = train_test_split(train, test, test_size=0.3, random_state=1)

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
train

ID  Year  Rank  Average  Bayes average  Users rated
0        30549  2008    91     7.62          7.518        96186
1        30549  2008    91     7.62          7.518        96186
2        30549  2008    91     7.62          7.518        96186
3        30549  2008    91     7.62          7.518        96186
4        30549  2008    91     7.62          7.518        96186
...        ...   ...   ...      ...            ...          ...
597745  104162  2012   104     7.70          7.458        21850
597746  104162  2012   104     7.70          7.458        21850
597747  104162  2012   104     7.70          7.458        21850
597748  104162  2012   104     7.70          7.458        21850
597749  104162  2012   104     7.70          7.458        21850

[597750 rows x 6 columns]

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
reg.coef_

array([ -0.21837411,  -0.64120193,   0.10089841,  16.72695044,
       -12.88149696,   1.14938401])

In [ ]:
reg.intercept_

7.179982984976122

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
import sklearn.metrics as metrics


In [ ]:
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

0.5386491438384559


In [ ]:
print(metrics.mean_squared_error(y_test,y_pred))

0.29014290015790156


In [ ]:
import math 


In [ ]:
math.sqrt(0.29014290015790156)

0.5386491438384559

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(y_test, y_pred))

In [ ]:
print(rmse)

0.5386491438384559
